# Generated by Django 3.1.3 on 2020-11-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='date',
            new_name='pub_date',
        ),
    ]
